changelog:
  exclude:
    labels:
      - skip-changelog
      - duplicate
      - invalid
      - question
    authors:
      - github-actions
      - dependabot
      - dependabot[bot]
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Docs
      labels:
        - documentation
        - docs
    - title: Maintenance
      labels:
        - chore
        - ci
        - dependencies
        - refactor
    - title: Other Changes
      labels:
        - "*"
